#cloud-config
write_files:
  - path: /usr/html/index.html
    content: |
      <html>
      Server 1
      </html>
runcmd:
  - yum install -y yum-utils device-mapper-persistent-data lvm2
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  = yum install -y docker-ce
  - systemctl start docker
  - docker run --name my-nginx2 -v /usr/html:/usr/share/nginx/html:ro -p 80:80 -d nginx
